language: dart
dart:
# Install the latest stable release
#- stable
# Install the latest dev release
- dev

notifications:
  email: false
#dart_task:
#   test
#- test: --platform vm
#- test: --platform chrome
# Warnings are fatal, but we only analyze the lib/ directory.
#- dartanalyzer: --fatal-warnings lib

script: pub run grinder test
#after_success: pub run coveralls var/lcov.info