name: esoko
version: 0.0.1
description: a general boileplate code for esoko app.
author: Elias Bundala <ebundala@gmail.com>
environment:
  sdk: '>=2.0.0-dev <2.0.0'
dependencies:
  redux: "^2.1.1"
  firebase_dart: "^0.7.6"
  web_socket_channel: "^1.0.7"
dev_dependencies:
  coveralls: ^2.1.0
  coverage: ^0.10.0
  grinder: ^0.8.1
  test: ^0.12.33



  
